remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: AmperPerchten Galerie
description: Eine Galerie der AmperPerchten
domain: galerie.feicht.bayern
url: https://galerie.feicht.bayern
github_username: feicht