remote_theme: pages-themes/slate@v0.2.0
# plugins:
# - jekyll-remote-theme
title: AmperPerchten Galerie
description: Eine Galerie der AmperPerchten
domain: feicht.github.io
url: https://feicht.github.io/
baseurl: /web-gallery
github_username: feicht